import { useState, useEffect } from 'react'

// Base path for GitHub Pages deployment
const BASE = import.meta.env.BASE_URL || '/'

/**
 * Custom hook to load property data and suburb GeoJSON.
 * Data files are generated by the Python scripts and committed
 * to public/data/ via GitHub Actions.
 */
export function usePropertyData() {
  const [properties, setProperties] = useState([])
  const [suburbs, setSuburbs] = useState(null)
  const [lastUpdated, setLastUpdated] = useState(null)
  const [dataNote, setDataNote] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  useEffect(() => {
    let cancelled = false

    async function loadData() {
      setLoading(true)
      setError(null)

      try {
        // Load property sales JSON
        const [propsRes, suburbsRes] = await Promise.all([
          fetch(`${BASE}data/properties.json`),
          fetch(`${BASE}data/suburbs.geojson`),
        ])

        if (!propsRes.ok) throw new Error(`Failed to load properties: ${propsRes.status}`)
        if (!suburbsRes.ok) throw new Error(`Failed to load suburb boundaries: ${suburbsRes.status}`)

        const propsData = await propsRes.json()
        const suburbsData = await suburbsRes.json()

        if (cancelled) return

        setProperties(propsData.properties || [])
        setLastUpdated(propsData.lastUpdated || null)
        setDataNote(propsData.note || null)
        setSuburbs(suburbsData)
      } catch (err) {
        if (!cancelled) {
          console.error('Data load error:', err)
          setError(err.message || 'Failed to load data')
        }
      } finally {
        if (!cancelled) setLoading(false)
      }
    }

    loadData()
    return () => { cancelled = true }
  }, [])

  return { properties, suburbs, lastUpdated, dataNote, loading, error }
}
